### ISSUE TITLE
Packet Loss Problem - Swift

### ISSUE THREAD

**Issue by adarshjayan7574** [quiet/QuietModemKit#14]
When transmitting long data (about 100 characters ) packet loss is about 90% .

Tried with 50 % volume
Please Help

**Comment by brian-armstrong** [comment]
Hi @adarshjayan7574 

Can you give more details on your setup and how you're measuring packet loss? What profile are you using?

**Comment by adarshjayan7574** [comment]
I was testing the ios code with the quiet js demo url. So whenever i tries to transfer data it shows about 70-90 percent packet loss, sometimes even 100%. Stil i can’t tranfer long text through this.

**Comment by brian-armstrong** [comment]
Unfortunately this isn't really enough info to go on. Feel free to open a new issue with descriptive report of devices/setup/profile etc
