### ISSUE TITLE
Which branch?

### ISSUE THREAD

**Issue by perfectdeveloper53** [quiet/QuietModemKit#16]
@brian-armstrong  Hi, I am happy to use this nice kit.
I am currently trying to use this repository but I see there is much difference in "devel" and "master"branch.
Which one is correct to use?

Thanks

**Comment by brian-armstrong** [comment]
Hi @perfectdeveloper53 

You should use the master branch.

**Comment by perfectdeveloper53** [comment]
@brian-armstrong  hi again.
I just tried to use winster's repository which you discussed on past issues.
https://github.com/quiet/QuietModemKit/issues/4

But I see, the app never called "receivercallback".
I can see that transmit works and I am able to see something hearing, but receivercallback not called.

May you give me some hints?  Thanks

**Comment by brian-armstrong** [comment]
@perfectdeveloper53 Can you give some more info about your setup? Are you receiving in the simulator or on a device? If it's a device, what model is it?

**Comment by perfectdeveloper53** [comment]
I tried simulator and device, both but i am unable to receive data through sound. It works with transmit so that I can hear something out.

device model : MC979CH/A

**Comment by brian-armstrong** [comment]
What kind of device is that?

Which modem profile are you using?

**Comment by perfectdeveloper53** [comment]
hi, i tried with "audible", "ultra-experiental" profiles.

I used iPad devices, version ; iOS 10.0, 9.3

**Comment by perfectdeveloper53** [comment]
@brian-armstrong  may you help me with this issue?
I tried but no luck yet.
